# Generated by Django 5.2.6 on 2025-11-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ecommerce',
            fields=[
                ('Product_Name', models.CharField(max_length=100)),
                ('Product_Price', models.FloatField()),
                ('Product_Manufacturer', models.CharField(max_length=30)),
                ('Product_Brand_Name', models.CharField(max_length=20)),
                ('Product_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Product_Quantity', models.IntegerField()),
                ('Product_Manufactured_Date', models.DateField()),
            ],
        ),
    ]
